apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: openpe-customer-a
  namespace: metallb-system
spec:
  myASN: 64515
  peerASN: 64514
  peerAddress: 172.16.20.1
  nodeSelectors:
    - matchLabels:
        node-role.kubernetes.io/worker: ""
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: openpe-customer-a-v6
  namespace: metallb-system
spec:
  myASN: 64515
  peerASN: 64514
  peerAddress: 2001:db8:20::1
  nodeSelectors:
    - matchLabels:
        node-role.kubernetes.io/worker: ""
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: customer-a-srv6-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - pool-customer-a
  peers:
    - openpe-customer-a
    - openpe-customer-a-v6
---
apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  name: receive-from-openpe-customer-a
  namespace: openshift-frr-k8s
spec:
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker: ""
  bgp:
    routers:
      - asn: 64515
        neighbors:
          - address: 172.16.20.1
            asn: 64514
            toReceive:
              allowed:
                mode: all
          - address: 2001:db8:20::1
            asn: 64514
            toReceive:
              allowed:
                mode: all
